"""Build the project SQLite database from data/raw/ and the generated inventory.

The pipeline is: read CSV -> validate against the schema in `schemas.py` ->
insert into an explicitly declared table -> assert the row count survived the
round trip. Validation failures are not caught. A bad input file aborts the
build with a pandera error naming the column and the offending rows, and the
database file is left absent rather than half-written.

Properties this module is responsible for, each covered by a test:

- **Reproducible.** The build is a pure function of the input files. It reads
  no clock, no environment, and no network, and it contains no randomness --
  the only randomness in the data layer is inside
  `scripts/generate_inventory.py`, which is seeded. Rebuilding from the same
  inputs produces the same content hashes.
- **No duplication.** Every table carries a primary key over its natural key,
  so a duplicated source row is rejected by SQLite rather than inserted twice.
  Row counts are asserted against `EXPECTED_ROW_COUNTS` after insert.
- **Referential integrity.** `machineID` is a real FOREIGN KEY, foreign key
  enforcement is on for the duration of the build, and the constraint is
  re-checked with `PRAGMA foreign_key_check` before commit.

Run:  python -m src.data.ingest [--raw data/raw] [--db data/pdm.db]
"""

from __future__ import annotations

import argparse
import hashlib
import json
import sqlite3
from pathlib import Path

import pandas as pd

from src.data.schemas import (
    EXPECTED_ROW_COUNTS,
    PARTS_INVENTORY_SCHEMA,
    SOURCE_SCHEMAS,
)

DEFAULT_RAW = Path("data/raw")
DEFAULT_DB = Path("data/pdm.db")
DEFAULT_INVENTORY = Path("data/generated/parts_inventory.csv")
DEFAULT_MANIFEST = Path("data/generated/build_manifest.json")

# Bumped by hand when the schema below changes, so a stale database can be
# detected instead of silently queried.
SCHEMA_VERSION = 1

DATETIME_FORMAT = "%Y-%m-%d %H:%M:%S"

DDL = """
PRAGMA foreign_keys = ON;

CREATE TABLE machines (
    machineID  INTEGER PRIMARY KEY,
    model      TEXT    NOT NULL,
    age        INTEGER NOT NULL
);

CREATE TABLE telemetry (
    machineID  INTEGER NOT NULL REFERENCES machines(machineID),
    datetime   TEXT    NOT NULL,
    volt       REAL    NOT NULL,
    rotate     REAL    NOT NULL,
    pressure   REAL    NOT NULL,
    vibration  REAL    NOT NULL,
    PRIMARY KEY (machineID, datetime)
);

CREATE TABLE errors (
    machineID  INTEGER NOT NULL REFERENCES machines(machineID),
    datetime   TEXT    NOT NULL,
    errorID    TEXT    NOT NULL,
    PRIMARY KEY (machineID, datetime, errorID)
);

CREATE TABLE maint (
    machineID  INTEGER NOT NULL REFERENCES machines(machineID),
    datetime   TEXT    NOT NULL,
    comp       TEXT    NOT NULL,
    PRIMARY KEY (machineID, datetime, comp)
);

-- `failure` holds a component identifier (comp1-comp4), not a boolean. The
-- column keeps its source name; see docs/DATA.md section 2.
CREATE TABLE failures (
    machineID  INTEGER NOT NULL REFERENCES machines(machineID),
    datetime   TEXT    NOT NULL,
    failure    TEXT    NOT NULL,
    PRIMARY KEY (machineID, datetime, failure)
);

-- Synthetic. Generated by scripts/generate_inventory.py from a fixed seed.
-- Not part of the Azure PdM dataset. See docs/DATA.md section 6.
CREATE TABLE parts_inventory (
    part_id            TEXT    PRIMARY KEY,
    component          TEXT    NOT NULL,
    compatible_models  TEXT    NOT NULL,
    stock_quantity     INTEGER NOT NULL,
    unit_cost          REAL    NOT NULL,
    supplier_id        TEXT    NOT NULL,
    lead_time_days     INTEGER NOT NULL
);

CREATE INDEX idx_telemetry_machine_time ON telemetry (machineID, datetime);
CREATE INDEX idx_errors_machine_time    ON errors    (machineID, datetime);
CREATE INDEX idx_maint_machine_time     ON maint     (machineID, datetime);
CREATE INDEX idx_failures_machine_time  ON failures  (machineID, datetime);

-- Time-first indexes support the temporal splits described in docs/DATA.md
-- section 5.2, which scan a date range across the whole fleet.
CREATE INDEX idx_telemetry_time ON telemetry (datetime);
CREATE INDEX idx_failures_time  ON failures  (datetime);

CREATE INDEX idx_inventory_component ON parts_inventory (component);
"""

# Column order used for INSERT, matching the DDL above.
INSERT_COLUMNS: dict[str, list[str]] = {
    "machines": ["machineID", "model", "age"],
    "telemetry": ["machineID", "datetime", "volt", "rotate", "pressure", "vibration"],
    "errors": ["machineID", "datetime", "errorID"],
    "maint": ["machineID", "datetime", "comp"],
    "failures": ["machineID", "datetime", "failure"],
    "parts_inventory": [
        "part_id",
        "component",
        "compatible_models",
        "stock_quantity",
        "unit_cost",
        "supplier_id",
        "lead_time_days",
    ],
}

# Deterministic insert order per table, so the on-disk B-tree layout is a
# function of the data alone.
SORT_KEYS: dict[str, list[str]] = {
    "machines": ["machineID"],
    "telemetry": ["machineID", "datetime"],
    "errors": ["machineID", "datetime", "errorID"],
    "maint": ["machineID", "datetime", "comp"],
    "failures": ["machineID", "datetime", "failure"],
    "parts_inventory": ["part_id"],
}


class IngestError(RuntimeError):
    """Raised when the build cannot proceed. Never caught inside this module."""


def load_source(raw: Path, table: str) -> pd.DataFrame:
    """Read one source CSV and validate it. Raises on any schema violation."""
    filename, schema = SOURCE_SCHEMAS[table]
    path = raw / filename
    if not path.exists():
        raise IngestError(
            f"source file missing: {path}. Place the Azure PdM CSVs in {raw}/ "
            f"(see docs/DATA.md section 1 for the download location)."
        )

    df = pd.read_csv(path)
    if "datetime" in df.columns:
        # Parsed here rather than in read_csv so that an unparseable value
        # surfaces as a pandas error on a named column, not a silent object
        # dtype that pandera would then reject with a less specific message.
        df["datetime"] = pd.to_datetime(df["datetime"], format="mixed")

    # `lazy=True` collects every violation instead of stopping at the first, so
    # one run reports the whole problem.
    return schema.validate(df, lazy=True)


def load_inventory(path: Path) -> pd.DataFrame:
    if not path.exists():
        raise IngestError(
            f"inventory missing: {path}. Run `python scripts/generate_inventory.py` "
            f"first, or `make data`, which does it for you."
        )
    return PARTS_INVENTORY_SCHEMA.validate(pd.read_csv(path), lazy=True)


def _to_rows(df: pd.DataFrame, table: str) -> list[tuple]:
    out = df.copy()
    if "datetime" in out.columns:
        out["datetime"] = out["datetime"].dt.strftime(DATETIME_FORMAT)
    out = out.sort_values(SORT_KEYS[table], ignore_index=True)
    return list(out[INSERT_COLUMNS[table]].itertuples(index=False, name=None))


def _content_hash(conn: sqlite3.Connection, table: str) -> str:
    """SHA-256 over the table's rows in primary-key order.

    Compares content across builds without depending on SQLite's file layout,
    which carries a version number and a change counter in its header.
    """
    order = ", ".join(SORT_KEYS[table])
    cols = ", ".join(INSERT_COLUMNS[table])
    digest = hashlib.sha256()
    for row in conn.execute(f"SELECT {cols} FROM {table} ORDER BY {order}"):
        digest.update(repr(row).encode("utf-8"))
    return digest.hexdigest()


def build(
    raw: Path = DEFAULT_RAW,
    db: Path = DEFAULT_DB,
    inventory: Path = DEFAULT_INVENTORY,
    manifest: Path | None = DEFAULT_MANIFEST,
    quiet: bool = False,
) -> dict[str, dict[str, object]]:
    """Rebuild `db` from scratch. Returns a per-table manifest."""

    def say(msg: str) -> None:
        if not quiet:
            print(msg)

    frames: dict[str, pd.DataFrame] = {}
    for table in SOURCE_SCHEMAS:
        say(f"validating {table} ...")
        frames[table] = load_source(raw, table)
        n = len(frames[table])
        expected = EXPECTED_ROW_COUNTS[table]
        if n != expected:
            raise IngestError(
                f"{table}: read {n:,} rows, expected {expected:,}. The source "
                f"file does not match the one documented in docs/DATA.md."
            )
        say(f"  {table}: {n:,} rows")

    say("validating parts_inventory ...")
    frames["parts_inventory"] = load_inventory(inventory)
    say(f"  parts_inventory: {len(frames['parts_inventory']):,} rows")

    # Rebuild from scratch. Never migrate in place: a partial migration is the
    # kind of state this pipeline exists to make impossible.
    db.parent.mkdir(parents=True, exist_ok=True)
    if db.exists():
        db.unlink()

    conn = sqlite3.connect(db)
    try:
        # Pinned so the file layout does not depend on the SQLite build's
        # compiled-in default page size.
        conn.execute("PRAGMA page_size = 4096")
        conn.executescript(DDL)
        conn.execute(f"PRAGMA user_version = {SCHEMA_VERSION}")

        # machines first: everything else references it.
        for table in ["machines", "telemetry", "errors", "maint", "failures", "parts_inventory"]:
            rows = _to_rows(frames[table], table)
            placeholders = ", ".join("?" * len(INSERT_COLUMNS[table]))
            cols = ", ".join(INSERT_COLUMNS[table])
            # Plain INSERT, not INSERT OR IGNORE: a duplicate must fail the
            # build, not vanish.
            conn.executemany(
                f"INSERT INTO {table} ({cols}) VALUES ({placeholders})", rows
            )
            say(f"inserted {len(rows):,} rows into {table}")

        violations = conn.execute("PRAGMA foreign_key_check").fetchall()
        if violations:
            raise IngestError(f"foreign key violations: {violations[:10]}")

        for table, expected in EXPECTED_ROW_COUNTS.items():
            (n,) = conn.execute(f"SELECT COUNT(*) FROM {table}").fetchone()
            if n != expected:
                raise IngestError(
                    f"{table}: {n:,} rows in database, expected {expected:,}"
                )

        conn.commit()
        conn.execute("VACUUM")

        result = {
            table: {
                "rows": conn.execute(f"SELECT COUNT(*) FROM {table}").fetchone()[0],
                "sha256": _content_hash(conn, table),
            }
            for table in INSERT_COLUMNS
        }
    finally:
        conn.close()

    if manifest is not None:
        manifest.parent.mkdir(parents=True, exist_ok=True)
        # No build timestamp: it would make the manifest differ between two
        # otherwise identical builds and defeat the point of writing it.
        manifest.write_text(
            json.dumps(
                {"schema_version": SCHEMA_VERSION, "tables": result},
                indent=2,
                sort_keys=True,
            )
            + "\n",
            encoding="utf-8",
        )
        say(f"wrote {manifest}")

    say(f"database ready: {db} ({db.stat().st_size:,} bytes)")
    return result


def main() -> None:
    parser = argparse.ArgumentParser(description="Build the PdM SQLite database.")
    parser.add_argument("--raw", type=Path, default=DEFAULT_RAW)
    parser.add_argument("--db", type=Path, default=DEFAULT_DB)
    parser.add_argument("--inventory", type=Path, default=DEFAULT_INVENTORY)
    parser.add_argument("--manifest", type=Path, default=DEFAULT_MANIFEST)
    args = parser.parse_args()

    result = build(args.raw, args.db, args.inventory, args.manifest)
    print()
    for table, info in result.items():
        print(f"  {table:<16} {info['rows']:>9,} rows  sha256={info['sha256'][:16]}")


if __name__ == "__main__":
    main()
